"""init book id is unique

Revision ID: 1f10e3baaebf
Revises: ce4db6a859c1
Create Date: 2024-01-28 17:09:58.733311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f10e3baaebf'
down_revision: Union[str, None] = 'ce4db6a859c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cart_items', ['book_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_items', type_='unique')
    # ### end Alembic commands ###
