"""init cart items book_id is not unique

Revision ID: 7c730a2bdb69
Revises: 1f10e3baaebf
Create Date: 2024-01-29 16:34:35.882479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c730a2bdb69'
down_revision: Union[str, None] = '1f10e3baaebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_items_book_id_key', 'cart_items', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('cart_items_book_id_key', 'cart_items', ['book_id'])
    # ### end Alembic commands ###
